-- MySQL Script generated by MySQL Workbench
-- Wed Jun 24 18:20:22 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `firstName` VARCHAR(45) NOT NULL COMMENT '',
  `lastName` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `createTime` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`idUser`)  COMMENT '',
  INDEX `USERNAMES` (`username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `roleName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idRole`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_has_Role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Role` (
  `User_idUser` INT NOT NULL COMMENT '',
  `Role_idRole` INT NOT NULL COMMENT '',
  PRIMARY KEY (`User_idUser`, `Role_idRole`)  COMMENT '',
  INDEX `fk_User_has_Role_Role1_idx` (`Role_idRole` ASC)  COMMENT '',
  INDEX `fk_User_has_Role_User_idx` (`User_idUser` ASC)  COMMENT '',
  CONSTRAINT `fk_User_has_Role_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Role_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `mydb`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Permission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Permission` (
  `idPermission` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `permissionName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idPermission`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role_has_Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Role_has_Permission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Role_has_Permission` (
  `Role_idRole` INT NOT NULL COMMENT '',
  `Permission_idPermission` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Role_idRole`, `Permission_idPermission`)  COMMENT '',
  INDEX `fk_Role_has_Permission_Permission1_idx` (`Permission_idPermission` ASC)  COMMENT '',
  INDEX `fk_Role_has_Permission_Role1_idx` (`Role_idRole` ASC)  COMMENT '',
  CONSTRAINT `fk_Role_has_Permission_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `mydb`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_has_Permission_Permission1`
    FOREIGN KEY (`Permission_idPermission`)
    REFERENCES `mydb`.`Permission` (`idPermission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Team` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `idTeam` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `teamName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTeam`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Team_has_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Team_has_User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Team_has_User` (
  `Team_idTeam` INT NOT NULL COMMENT '',
  `User_idUser` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Team_idTeam`, `User_idUser`)  COMMENT '',
  INDEX `fk_Team_has_User_User1_idx` (`User_idUser` ASC)  COMMENT '',
  INDEX `fk_Team_has_User_Team1_idx` (`Team_idTeam` ASC)  COMMENT '',
  CONSTRAINT `fk_Team_has_User_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Problem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Problem` (
  `idProblem` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `problemName` VARCHAR(45) NOT NULL COMMENT '',
  `problemFileAddress` VARCHAR(255) NOT NULL COMMENT '',
  `specialJudge` VARCHAR(255) NULL COMMENT '',
  `setter_idUser` INT NOT NULL COMMENT '',
  `memoryLimit` INT NOT NULL COMMENT '',
  `timeLimit` FLOAT NOT NULL COMMENT '',
  PRIMARY KEY (`idProblem`)  COMMENT '',
  INDEX `fk_Problem_User1_idx` (`setter_idUser` ASC)  COMMENT '',
  CONSTRAINT `fk_Problem_User1`
    FOREIGN KEY (`setter_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TestData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TestData` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TestData` (
  `idTestData` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `inputAddress` VARCHAR(255) NULL COMMENT '',
  `outputAddress` VARCHAR(255) NULL COMMENT '',
  `Problem_idProblem` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idTestData`, `Problem_idProblem`)  COMMENT '',
  INDEX `fk_TestData_Problem1_idx` (`Problem_idProblem` ASC)  COMMENT '',
  CONSTRAINT `fk_TestData_Problem1`
    FOREIGN KEY (`Problem_idProblem`)
    REFERENCES `mydb`.`Problem` (`idProblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tagName` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTag`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Problem_has_Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Problem_has_Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Problem_has_Tag` (
  `Problem_idProblem` INT NOT NULL COMMENT '',
  `Tag_idTag` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Problem_idProblem`, `Tag_idTag`)  COMMENT '',
  INDEX `fk_Problem_has_Tag_Tag1_idx` (`Tag_idTag` ASC)  COMMENT '',
  INDEX `fk_Problem_has_Tag_Problem1_idx` (`Problem_idProblem` ASC)  COMMENT '',
  CONSTRAINT `fk_Problem_has_Tag_Problem1`
    FOREIGN KEY (`Problem_idProblem`)
    REFERENCES `mydb`.`Problem` (`idProblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Problem_has_Tag_Tag1`
    FOREIGN KEY (`Tag_idTag`)
    REFERENCES `mydb`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scoreboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Scoreboard` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Scoreboard` (
  `idScoreboard` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `scoreboardFileAddress` VARCHAR(225) NULL COMMENT '',
  PRIMARY KEY (`idScoreboard`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Site` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `idSite` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `siteName` VARCHAR(45) NULL COMMENT '',
  `Scoreboard_idScoreboard` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idSite`)  COMMENT '',
  INDEX `fk_Site_Scoreboard1_idx` (`Scoreboard_idScoreboard` ASC)  COMMENT '',
  CONSTRAINT `fk_Site_Scoreboard1`
    FOREIGN KEY (`Scoreboard_idScoreboard`)
    REFERENCES `mydb`.`Scoreboard` (`idScoreboard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Judge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Judge` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Judge` (
  `Site_idSite` INT NOT NULL COMMENT '',
  `User_idUser` INT NOT NULL COMMENT '',
  `Problem_idProblem` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Site_idSite`, `User_idUser`, `Problem_idProblem`)  COMMENT '',
  INDEX `fk_Site_has_User_User1_idx` (`User_idUser` ASC)  COMMENT '',
  INDEX `fk_Site_has_User_Site1_idx` (`Site_idSite` ASC)  COMMENT '',
  INDEX `fk_Site_has_User_Problem1_idx` (`Problem_idProblem` ASC)  COMMENT '',
  CONSTRAINT `fk_Site_has_User_Site1`
    FOREIGN KEY (`Site_idSite`)
    REFERENCES `mydb`.`Site` (`idSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Site_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Site_has_User_Problem1`
    FOREIGN KEY (`Problem_idProblem`)
    REFERENCES `mydb`.`Problem` (`idProblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contest` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contest` (
  `idContest` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `contestName` VARCHAR(45) NULL COMMENT '',
  `startTime` DATETIME NULL COMMENT '',
  `endTime` DATETIME NULL COMMENT '',
  `manager_idUser` INT NOT NULL COMMENT '',
  `isAssignment` TINYINT(1) NULL COMMENT '',
  `Site_idSite` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idContest`)  COMMENT '',
  INDEX `fk_Contest_User1_idx` (`manager_idUser` ASC)  COMMENT '',
  INDEX `fk_Contest_Site1_idx` (`Site_idSite` ASC)  COMMENT '',
  CONSTRAINT `fk_Contest_User1`
    FOREIGN KEY (`manager_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contest_Site1`
    FOREIGN KEY (`Site_idSite`)
    REFERENCES `mydb`.`Site` (`idSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contest_has_Problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contest_has_Problem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contest_has_Problem` (
  `Contest_idContest` INT NOT NULL COMMENT '',
  `Problem_idProblem` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Contest_idContest`, `Problem_idProblem`)  COMMENT '',
  INDEX `fk_Contest_has_Problem_Problem1_idx` (`Problem_idProblem` ASC)  COMMENT '',
  INDEX `fk_Contest_has_Problem_Contest1_idx` (`Contest_idContest` ASC)  COMMENT '',
  CONSTRAINT `fk_Contest_has_Problem_Contest1`
    FOREIGN KEY (`Contest_idContest`)
    REFERENCES `mydb`.`Contest` (`idContest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contest_has_Problem_Problem1`
    FOREIGN KEY (`Problem_idProblem`)
    REFERENCES `mydb`.`Problem` (`idProblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Submission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Submission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Submission` (
  `Team_idTeam` INT NOT NULL COMMENT '',
  `Site_idSite` INT NOT NULL COMMENT '',
  `Problem_idProblem` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Team_idTeam`, `Site_idSite`, `Problem_idProblem`)  COMMENT '',
  INDEX `fk_Team_has_Site_Site1_idx` (`Site_idSite` ASC)  COMMENT '',
  INDEX `fk_Team_has_Site_Team1_idx` (`Team_idTeam` ASC)  COMMENT '',
  INDEX `fk_Team_has_Site_Problem1_idx` (`Problem_idProblem` ASC)  COMMENT '',
  CONSTRAINT `fk_Team_has_Site_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_has_Site_Site1`
    FOREIGN KEY (`Site_idSite`)
    REFERENCES `mydb`.`Site` (`idSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_has_Site_Problem1`
    FOREIGN KEY (`Problem_idProblem`)
    REFERENCES `mydb`.`Problem` (`idProblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
